apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  labels:
    app: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 'weather-app'
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: flask-app
        image: oriamrani/weather-app:latest
        ports:
        - containerPort: 8000
